/**
 * The model registry and the downloader (models.ts). Nothing here touches the network: the
 * downloader is pointed at a loopback server serving generated bytes, and the guard that keeps
 * tests and CI from fetching a real model is itself tested.
 */

import { afterEach, describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  utimesSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import {
  ChecksumError,
  DownloadRefused,
  defaultModelsDir,
  downloadFile,
  downloadModels,
  hostPlatform,
  MODELS,
  type ModelSpecEntry,
  modelFile,
  modelsFor,
  NEMOTRON,
  NEMOTRON_FILE,
  networkForbidden,
  pruneRetiredModels,
  RECOGNIZER,
  RETIRED_MODELS,
  verifyModels,
} from "../src/main/asr/models.ts";
import { recognizerConfig, SherpaRecognizer, writeBpeVocab } from "../src/main/asr/sherpa.ts";
import { tempDir } from "./helpers.ts";

const cleanups: (() => void)[] = [];
afterEach(() => {
  for (const c of cleanups.splice(0)) c();
});

function dir(): string {
  const t = tempDir();
  cleanups.push(t.cleanup);
  return t.dir;
}

const sha = (b: Uint8Array) => createHash("sha256").update(b).digest("hex");

/** A loopback server for one file, recording the Range headers it saw; can cut a body short. */
function serve(body: Uint8Array, o: { cutAt?: number; ignoreRange?: boolean } = {}) {
  const ranges: (string | null)[] = [];
  let cut = o.cutAt;
  const server = Bun.serve({
    port: 0,
    hostname: "127.0.0.1",
    fetch(req) {
      const range = req.headers.get("range");
      ranges.push(range);
      let from = 0;
      if (range && !o.ignoreRange) from = Number(/bytes=(\d+)-/.exec(range)?.[1] ?? 0);
      let slice = body.subarray(from);
      if (cut !== undefined) {
        slice = slice.subarray(0, cut);
        cut = undefined;
      }
      return new Response(slice, { status: from > 0 ? 206 : 200 });
    },
  });
  cleanups.push(() => server.stop(true));
  return { url: `http://127.0.0.1:${server.port}/model.onnx`, ranges };
}

describe("the registry", () => {
  test("every file has an https URL pinned to a revision, a SHA-256, a size and a licence", () => {
    // The five sherpa and helper models, then Qwen and its llama-server builds (asr-llama.test.ts).
    expect(MODELS.filter((m) => !m.onDemand).map((m) => m.id)).toEqual([
      RECOGNIZER,
      "silero-vad",
      NEMOTRON,
      "pyannote-segmentation-3.0",
      "titanet-small",
    ]);
    expect(MODELS.filter((m) => m.onDemand)[0]?.id).toBe("qwen3-asr-1.7b");
    for (const m of MODELS) {
      expect(m.licence).toMatch(/^(MIT|CC-BY-4\.0|Apache-2\.0|OpenMDW-1\.1)$/);
      expect(m.source).toMatch(/^https:\/\//);
      for (const f of m.files) {
        expect(f.url).toMatch(/^https:\/\//);
        expect(f.url).not.toMatch(/\/(main|master|latest)\//);
        expect(f.sha256).toMatch(/^[0-9a-f]{64}$/);
        expect(f.size).toBeGreaterThan(0);
      }
    }
    // The recognizer ships its tokenizer, from which biasing builds its bpe.vocab.
    const names = MODELS[0]?.files.map((f) => f.name);
    expect(names).toContain("tokenizer.json");
    expect(names).toContain("tokens.txt");
  });

  test("Nemotron is the 400 MB ONNX export pinned to a revision, under NVIDIA's OpenMDW licence", () => {
    const m = MODELS.find((x) => x.id === NEMOTRON);
    expect(m?.licence).toBe("OpenMDW-1.1");
    expect(m?.source).toBe("https://huggingface.co/nvidia/Nemotron-3-Diarization");
    expect(m?.files).toEqual([
      {
        name: NEMOTRON_FILE,
        url: expect.stringMatching(/\/resolve\/[0-9a-f]{40}\/nemotron-3-diarization\//),
        sha256: "915e4fa23b0192ed9fadeb1cdd26847df986d50c92012d177be28d0343bbe03a",
        size: 400506656,
      },
    ]);
  });

  test("the diarize CI job smokes the same Nemotron file the registry pins", () => {
    const pin = (yml: string) => ({
      url: /^\s*MODEL_URL:\s*(\S+)\s*$/m.exec(yml)?.[1],
      sha256: /^\s*MODEL_SHA256:\s*(\S+)\s*$/m.exec(yml)?.[1],
    });
    const f = MODELS.find((x) => x.id === NEMOTRON)?.files[0];
    // The PR smoke (ci.yml) and the nightly evaluation (nightly.yml) both fetch it.
    for (const wf of ["ci.yml", "nightly.yml"]) {
      const text = readFileSync(join(import.meta.dir, "..", ".github", "workflows", wf), "utf8");
      expect({ wf, ...pin(text) }).toEqual({ wf, url: f?.url, sha256: f?.sha256 });
    }
    const yml = readFileSync(join(import.meta.dir, "..", ".github", "workflows", "ci.yml"), "utf8");
    // Positive control: a pin bumped on one side only is caught.
    const bumped = yml.replace(f?.sha256 as string, "0".repeat(64));
    expect(pin(bumped)).not.toEqual({ url: f?.url, sha256: f?.sha256 });
  });

  test("a machine downloads only what its asr.diarizer needs", () => {
    const ids = (k: "nemotron" | "embeddings") =>
      modelsFor({ "asr.diarizer": k }, hostPlatform()).map((m) => m.id);
    // TitaNet stays with Nemotron: it carries names across a stream that starts over.
    expect(ids("nemotron")).toEqual([RECOGNIZER, "silero-vad", NEMOTRON, "titanet-small"]);
    expect(ids("embeddings")).toEqual([
      RECOGNIZER,
      "silero-vad",
      "pyannote-segmentation-3.0",
      "titanet-small",
    ]);
    // Every model is needed by one choice or the other: none is fetched for nothing. The on-demand
    // entries (Qwen and its runtime) come only when a job or a pull names them.
    const used = new Set([...ids("nemotron"), ...ids("embeddings")]);
    expect(MODELS.filter((m) => !m.onDemand).every((m) => used.has(m.id))).toBe(true);
    expect(MODELS.filter((m) => m.onDemand).some((m) => used.has(m.id))).toBe(false);
  });

  test("a retired model is never a current one, and pruning removes only the retired folders", () => {
    const current = new Set(MODELS.map((m) => m.id));
    expect(RETIRED_MODELS.length).toBeGreaterThan(0);
    for (const id of RETIRED_MODELS) expect(current.has(id)).toBe(false);
    const d = dir();
    for (const id of [...RETIRED_MODELS, RECOGNIZER, "mine"]) {
      mkdirSync(join(d, id), { recursive: true });
      writeFileSync(join(d, id, "f.onnx"), "x");
    }
    expect(pruneRetiredModels(d)).toEqual([...RETIRED_MODELS]);
    for (const id of RETIRED_MODELS) expect(existsSync(join(d, id))).toBe(false);
    expect(existsSync(join(d, RECOGNIZER, "f.onnx"))).toBe(true);
    expect(existsSync(join(d, "mine", "f.onnx"))).toBe(true);
    // Nothing left to remove the second time.
    expect(pruneRetiredModels(d)).toEqual([]);
  });

  test("the models folder is per user and AKOU_MODELS_DIR overrides it", () => {
    expect(defaultModelsDir({ AKOU_MODELS_DIR: "/x/models" }, "linux")).toBe("/x/models");
    expect(defaultModelsDir({ XDG_DATA_HOME: "/d" }, "linux")).toBe(join("/d", "akou", "models"));
    expect(defaultModelsDir({}, "darwin")).toContain(join("Application Support", "akou", "models"));
  });
});

describe("tests and CI never download", () => {
  test("under bun test the guard is on", () => {
    expect(networkForbidden()).toBe(true);
    expect(networkForbidden({ CI: "true" })).toBe(true);
    expect(networkForbidden({})).toBe(false);
  });

  test("a real model URL is refused before any request is made", async () => {
    let fetched = false;
    const f = MODELS[1]?.files[0];
    if (!f) throw new Error("no file");
    const err = await downloadFile("silero-vad", f, join(dir(), "x.onnx"), {
      fetch: (async () => {
        fetched = true;
        return new Response("");
      }) as unknown as typeof fetch,
    }).catch((e) => e);
    expect(err).toBeInstanceOf(DownloadRefused);
    expect(fetched).toBe(false);
  });
});

describe("the downloader", () => {
  const body = new Uint8Array(200_000).map((_, i) => (i * 31) % 251);
  const spec = (url: string, over: Partial<{ sha256: string; size: number }> = {}) => ({
    name: "model.onnx",
    url,
    sha256: sha(body),
    size: body.length,
    ...over,
  });

  test("a file is moved into place only after its SHA-256 matches", async () => {
    const s = serve(body);
    const path = join(dir(), "m", "model.onnx");
    await downloadFile("m", spec(s.url), path);
    expect(sha(new Uint8Array(readFileSync(path)))).toBe(sha(body));
    expect(existsSync(`${path}.part`)).toBe(false);
  });

  test("an interrupted download resumes from the .part file with a Range request", async () => {
    const s = serve(body, { cutAt: 50_000 });
    const path = join(dir(), "model.onnx");
    // The first attempt gets a short body and fails the check, keeping nothing half-verified.
    await expect(downloadFile("m", spec(s.url), path)).rejects.toBeInstanceOf(ChecksumError);
    expect(existsSync(path)).toBe(false);
    // A partial file left by a crash is resumed, not refetched.
    writeFileSync(`${path}.part`, body.subarray(0, 120_000));
    await downloadFile("m", spec(s.url), path);
    expect(s.ranges.at(-1)).toBe("bytes=120000-");
    expect(statSync(path).size).toBe(body.length);
  });

  test("a server that ignores the range restarts the file instead of corrupting it", async () => {
    const s = serve(body, { ignoreRange: true });
    const path = join(dir(), "model.onnx");
    writeFileSync(`${path}.part`, body.subarray(0, 1000));
    await downloadFile("m", spec(s.url), path);
    expect(sha(new Uint8Array(readFileSync(path)))).toBe(sha(body));
  });

  test("a checksum mismatch deletes the partial file and throws", async () => {
    const s = serve(body);
    const path = join(dir(), "model.onnx");
    const err = await downloadFile("m", spec(s.url, { sha256: "0".repeat(64) }), path).catch(
      (e) => e,
    );
    expect(err).toBeInstanceOf(ChecksumError);
    expect(String(err.message)).toContain("does not match the pinned");
    expect(existsSync(path)).toBe(false);
    expect(existsSync(`${path}.part`)).toBe(false);
  });

  test("downloadModels skips verified files and verifyModels reports each state", async () => {
    const s = serve(body);
    const d = dir();
    const registry: ModelSpecEntry[] = [
      { id: "m", job: "test", licence: "MIT", source: "https://example.org", files: [spec(s.url)] },
    ];
    await downloadModels(d, ["m"], { registry });
    const before = s.ranges.length;
    await downloadModels(d, ["m"], { registry });
    expect(s.ranges.length).toBe(before);

    const real = dir();
    const states = await verifyModels(real, ["silero-vad"]);
    expect(states).toEqual([
      {
        model: "silero-vad",
        name: "silero_vad.onnx",
        path: modelFile(real, "silero-vad", "silero_vad.onnx"),
        state: "missing",
      },
    ]);
    mkdirSync(join(real, "silero-vad"), { recursive: true });
    writeFileSync(modelFile(real, "silero-vad", "silero_vad.onnx"), "not a model");
    expect((await verifyModels(real, ["silero-vad"]))[0]?.state).toBe("size");
  });
});

describe("[spike] Hotwords to a non-transducer model kill the process: the sherpa-onnx guard", () => {
  // A stub in place of the native recognizer: the guard must refuse before any stream exists.
  function stub() {
    const calls: unknown[][] = [];
    const rec = {
      createStream: (...args: unknown[]) => {
        calls.push(args);
        return { acceptWaveform: () => {} };
      },
      decode: () => {},
      getResult: () => ({ text: " ok " }),
    };
    return { rec, calls };
  }
  const audio = new Float32Array(16000);

  test("an empty hotword string and any hotwords to a non-transducer throw before createStream", () => {
    const a = stub();
    const parakeet = new SherpaRecognizer(RECOGNIZER, a.rec, "beam");
    expect(() => parakeet.decode(audio, "")).toThrow(/refusing hotwords/);
    const b = stub();
    const moonshine = new SherpaRecognizer("moonshine-base", b.rec, "beam");
    expect(moonshine.kind).not.toBe("transducer");
    expect(() => moonshine.decode(audio, "Hetzner")).toThrow(/refusing hotwords/);
    expect([...a.calls, ...b.calls]).toEqual([]);
  });

  test("positive control: a transducer with hotwords, and any model without, reach createStream", () => {
    const a = stub();
    const parakeet = new SherpaRecognizer(RECOGNIZER, a.rec, "beam");
    expect(parakeet.decode(audio, "Hetzner").text).toBe("ok");
    expect(parakeet.decode(audio).text).toBe("ok");
    const b = stub();
    new SherpaRecognizer("moonshine-base", b.rec, "beam").decode(audio);
    expect(a.calls).toEqual([["Hetzner"], []]);
    expect(b.calls).toEqual([[]]);
  });
});

describe("Parakeet decodes greedy; hotwords only with beam, at 1.5 (asr.parakeet.decoding)", () => {
  const file = (name: string) => `/m/${name}`;

  test("greedy: greedy_search, no hotword score, no bpe.vocab", () => {
    const c = recognizerConfig(file, 2, { decoding: "greedy" });
    expect(c.decodingMethod).toBe("greedy_search");
    expect(c).not.toHaveProperty("hotwordsScore");
    expect(c).not.toHaveProperty("maxActivePaths");
    expect(c.modelConfig).not.toHaveProperty("bpeVocab");
    expect(c.modelConfig).not.toHaveProperty("modelingUnit");
    expect(c.modelConfig).toMatchObject({ tokens: "/m/tokens.txt", numThreads: 2 });
  });

  test("beam: modified_beam_search with the bpe.vocab and hotwords at 1.5", () => {
    const c = recognizerConfig(file, 4, { decoding: "beam", bpeVocab: "/c/bpe-x.vocab" });
    expect(c.decodingMethod).toBe("modified_beam_search");
    expect(c.hotwordsScore).toBe(1.5);
    expect(c.maxActivePaths).toBe(4);
    expect(c.modelConfig).toMatchObject({
      modelingUnit: "bpe",
      bpeVocab: "/c/bpe-x.vocab",
      numThreads: 4,
    });
  });

  test("a greedy recognizer refuses hotwords before createStream, and decodes without them", () => {
    const calls: unknown[][] = [];
    const rec = {
      createStream: (...args: unknown[]) => {
        calls.push(args);
        return { acceptWaveform: () => {} };
      },
      decode: () => {},
      getResult: () => ({ text: " ok " }),
    };
    const greedy = new SherpaRecognizer(RECOGNIZER, rec, "greedy");
    expect(() => greedy.decode(new Float32Array(16000), "Hetzner")).toThrow(/greedy/);
    expect(greedy.decode(new Float32Array(16000)).text).toBe("ok");
    expect(calls).toEqual([[]]);
  });
});

describe("the hotword vocabulary file two Workers share", () => {
  // The live Worker and the final-pass Worker can each write the same content-addressed file while
  // the other is creating its recognizer from it; sherpa-onnx exits the process on a torn file.
  test("a complete file already in place is never rewritten, so a reader never sees it truncated", () => {
    const d = dir();
    const path = writeBpeVocab(d, "\u2581Het -1\nzner -1\n");
    const past = new Date(Date.UTC(2020, 0, 1));
    utimesSync(path, past, past);
    expect(writeBpeVocab(d, "\u2581Het -1\nzner -1\n")).toBe(path);
    expect(statSync(path).mtimeMs).toBe(past.getTime());
    expect(readdirSync(d)).toEqual([path.slice(d.length + 1)]);
  });

  test("a file under the right name with the wrong bytes is replaced whole, leaving no temporary", () => {
    const d = dir();
    const path = writeBpeVocab(d, "\u2581Het -1\nzner -1\n");
    writeFileSync(path, "\u2581He");
    expect(writeBpeVocab(d, "\u2581Het -1\nzner -1\n")).toBe(path);
    expect(readFileSync(path, "utf8")).toBe("\u2581Het -1\nzner -1\n");
    expect(readdirSync(d)).toEqual([path.slice(d.length + 1)]);
  });
});
