/**
 * The model registry and the downloader (models.ts). Nothing here touches the network: the
 * downloader is pointed at a loopback server serving generated bytes, and the guard that keeps
 * tests and CI from fetching a real model is itself tested.
 */

import { afterEach, describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  ChecksumError,
  DownloadRefused,
  defaultModelsDir,
  downloadFile,
  downloadModels,
  MODELS,
  type ModelSpecEntry,
  modelFile,
  networkForbidden,
  RECOGNIZER,
  verifyModels,
} from "../src/main/asr/models.ts";
import { tempDir } from "./helpers.ts";

const cleanups: (() => void)[] = [];
afterEach(() => {
  for (const c of cleanups.splice(0)) c();
});

function dir(): string {
  const t = tempDir();
  cleanups.push(t.cleanup);
  return t.dir;
}

const sha = (b: Uint8Array) => createHash("sha256").update(b).digest("hex");

/** A loopback server for one file, recording the Range headers it saw; can cut a body short. */
function serve(body: Uint8Array, o: { cutAt?: number; ignoreRange?: boolean } = {}) {
  const ranges: (string | null)[] = [];
  let cut = o.cutAt;
  const server = Bun.serve({
    port: 0,
    hostname: "127.0.0.1",
    fetch(req) {
      const range = req.headers.get("range");
      ranges.push(range);
      let from = 0;
      if (range && !o.ignoreRange) from = Number(/bytes=(\d+)-/.exec(range)?.[1] ?? 0);
      let slice = body.subarray(from);
      if (cut !== undefined) {
        slice = slice.subarray(0, cut);
        cut = undefined;
      }
      return new Response(slice, { status: from > 0 ? 206 : 200 });
    },
  });
  cleanups.push(() => server.stop(true));
  return { url: `http://127.0.0.1:${server.port}/model.onnx`, ranges };
}

describe("the registry", () => {
  test("every file has an https URL pinned to a revision, a SHA-256, a size and a licence", () => {
    expect(MODELS.map((m) => m.id)).toEqual([
      RECOGNIZER,
      "silero-vad",
      "pyannote-segmentation-3.0",
      "titanet-small",
    ]);
    for (const m of MODELS) {
      expect(m.licence).toMatch(/^(MIT|CC-BY-4\.0|Apache-2\.0)$/);
      expect(m.source).toMatch(/^https:\/\//);
      for (const f of m.files) {
        expect(f.url).toMatch(/^https:\/\//);
        expect(f.url).not.toMatch(/\/(main|master|latest)\//);
        expect(f.sha256).toMatch(/^[0-9a-f]{64}$/);
        expect(f.size).toBeGreaterThan(0);
      }
    }
    // The recognizer ships its tokenizer, from which biasing builds its bpe.vocab.
    const names = MODELS[0]?.files.map((f) => f.name);
    expect(names).toContain("tokenizer.json");
    expect(names).toContain("tokens.txt");
  });

  test("the models folder is per user and AKOU_MODELS_DIR overrides it", () => {
    expect(defaultModelsDir({ AKOU_MODELS_DIR: "/x/models" }, "linux")).toBe("/x/models");
    expect(defaultModelsDir({ XDG_DATA_HOME: "/d" }, "linux")).toBe(join("/d", "akou", "models"));
    expect(defaultModelsDir({}, "darwin")).toContain(join("Application Support", "akou", "models"));
  });
});

describe("tests and CI never download", () => {
  test("under bun test the guard is on", () => {
    expect(networkForbidden()).toBe(true);
    expect(networkForbidden({ CI: "true" })).toBe(true);
    expect(networkForbidden({})).toBe(false);
  });

  test("a real model URL is refused before any request is made", async () => {
    let fetched = false;
    const f = MODELS[1]?.files[0];
    if (!f) throw new Error("no file");
    const err = await downloadFile("silero-vad", f, join(dir(), "x.onnx"), {
      fetch: (async () => {
        fetched = true;
        return new Response("");
      }) as unknown as typeof fetch,
    }).catch((e) => e);
    expect(err).toBeInstanceOf(DownloadRefused);
    expect(fetched).toBe(false);
  });
});

describe("the downloader", () => {
  const body = new Uint8Array(200_000).map((_, i) => (i * 31) % 251);
  const spec = (url: string, over: Partial<{ sha256: string; size: number }> = {}) => ({
    name: "model.onnx",
    url,
    sha256: sha(body),
    size: body.length,
    ...over,
  });

  test("a file is moved into place only after its SHA-256 matches", async () => {
    const s = serve(body);
    const path = join(dir(), "m", "model.onnx");
    await downloadFile("m", spec(s.url), path);
    expect(sha(new Uint8Array(readFileSync(path)))).toBe(sha(body));
    expect(existsSync(`${path}.part`)).toBe(false);
  });

  test("an interrupted download resumes from the .part file with a Range request", async () => {
    const s = serve(body, { cutAt: 50_000 });
    const path = join(dir(), "model.onnx");
    // The first attempt gets a short body and fails the check, keeping nothing half-verified.
    await expect(downloadFile("m", spec(s.url), path)).rejects.toBeInstanceOf(ChecksumError);
    expect(existsSync(path)).toBe(false);
    // A partial file left by a crash is resumed, not refetched.
    writeFileSync(`${path}.part`, body.subarray(0, 120_000));
    await downloadFile("m", spec(s.url), path);
    expect(s.ranges.at(-1)).toBe("bytes=120000-");
    expect(statSync(path).size).toBe(body.length);
  });

  test("a server that ignores the range restarts the file instead of corrupting it", async () => {
    const s = serve(body, { ignoreRange: true });
    const path = join(dir(), "model.onnx");
    writeFileSync(`${path}.part`, body.subarray(0, 1000));
    await downloadFile("m", spec(s.url), path);
    expect(sha(new Uint8Array(readFileSync(path)))).toBe(sha(body));
  });

  test("a checksum mismatch deletes the partial file and throws", async () => {
    const s = serve(body);
    const path = join(dir(), "model.onnx");
    const err = await downloadFile("m", spec(s.url, { sha256: "0".repeat(64) }), path).catch(
      (e) => e,
    );
    expect(err).toBeInstanceOf(ChecksumError);
    expect(String(err.message)).toContain("does not match the pinned");
    expect(existsSync(path)).toBe(false);
    expect(existsSync(`${path}.part`)).toBe(false);
  });

  test("downloadModels skips verified files and verifyModels reports each state", async () => {
    const s = serve(body);
    const d = dir();
    const registry: ModelSpecEntry[] = [
      { id: "m", job: "test", licence: "MIT", source: "https://example.org", files: [spec(s.url)] },
    ];
    await downloadModels(d, ["m"], { registry });
    const before = s.ranges.length;
    await downloadModels(d, ["m"], { registry });
    expect(s.ranges.length).toBe(before);

    const real = dir();
    const states = await verifyModels(real, ["silero-vad"]);
    expect(states).toEqual([
      {
        model: "silero-vad",
        name: "silero_vad.onnx",
        path: modelFile(real, "silero-vad", "silero_vad.onnx"),
        state: "missing",
      },
    ]);
    mkdirSync(join(real, "silero-vad"), { recursive: true });
    writeFileSync(modelFile(real, "silero-vad", "silero_vad.onnx"), "not a model");
    expect((await verifyModels(real, ["silero-vad"]))[0]?.state).toBe("size");
  });
});
