//! The macOS inserter of `akou-capture dictate` (docs/ux/DICTATION.md DC-N6, DC-N7, DC-N8): the
//! general pasteboard behind `insert::Clipboard` and the key events behind `insert::Sink`. The
//! receipt rules themselves are in `insert`, the same on every OS.
//!
//! - **The promise.** A paste publishes the text with `declareTypes:owner:`, so the pasteboard
//!   holds a promise, not the text; when an app reads it, AppKit asks the owner
//!   (`pasteboard:provideDataForType:`), and that call is the read receipt. Only a read of the
//!   text counts: a read of a marker type is a clipboard manager looking at the markers. The
//!   promise is marked transient, concealed and generated (nspasteboard.org), so a well-behaved
//!   clipboard manager neither keeps nor shows it.
//! - **The main run loop.** AppKit serves a promise only on the main thread's run loop, whichever
//!   thread declared it (measured in docs/gates/dc-n6-mac-paste-promise.md). The worker loop runs
//!   on the main thread, and `wait` turns the main run loop while it waits for its next message,
//!   so a read is answered within one step. The keyboard layout calls (`TIS*`) need the main
//!   thread as well.
//! - **The snapshot** is every type of every item, read before the promise replaces them; the
//!   restore writes the same items back. A snapshot key is `index<TAB>type`.
//! - **The events** come from a private event source (`kCGEventSourceStatePrivate`), so the
//!   user's own held keys do not leak into them, and each carries `mac::AKOU_EVENT` so the
//!   helper's own tap lets it pass. A chord is its modifiers down, the key down and up with the
//!   modifiers' flags, then the modifiers up, posted at the HID level. The V of the paste chord is
//!   looked up on the active layout with Command held (`UCKeyTranslate`), so Dvorak gets its own
//!   V and "Dvorak - QWERTY Command" gets the QWERTY one; a layout that types no V at all (Russian,
//!   Greek) falls back to the ASCII-capable layout macOS itself uses for shortcuts. There is no
//!   assumed key code.
//! - **The typed path** is one key-down and key-up per piece, each with the piece as its Unicode
//!   string (`CGEventKeyboardSetUnicodeString`, at most `TYPE_CHUNK` UTF-16 units).
//! - **No grant, no events.** Without the Accessibility grant macOS drops posted events without a
//!   word, so a press answers `no-grant` at once and the paste settles as a failed chord.
//!
//! The tests here build events and never post them; the pasteboard and the layouts are exercised
//! on a private named pasteboard by `tests/mac_pasteboard.rs`, and a real paste into a real text
//! view runs only on the CI macOS runner (`.github/workflows/ci.yml`).

use std::cell::RefCell;
use std::ffi::c_void;
use std::rc::Rc;
use std::sync::mpsc::{Receiver, RecvTimeoutError, TryRecvError};
use std::time::Duration;

use objc2::rc::{Retained, autoreleasepool};
use objc2::runtime::{AnyClass, AnyObject, NSObject};
use objc2::{AnyThread, DefinedClass, define_class, msg_send};
use objc2_core_foundation::{
    CFRetained, CFRunLoop, CFRunLoopRunResult, CFString, kCFRunLoopDefaultMode,
};
use objc2_core_graphics::{
    CGEvent, CGEventField, CGEventFlags, CGEventSource, CGEventSourceStateID, CGEventTapLocation,
    CGEventType,
};
use objc2_foundation::{NSArray, NSData, NSString};

use super::insert::{Clipboard, Key, Sink, Snapshot, TYPE_CHUNK};
use super::live::Msg;
use super::mac::{AKOU_EVENT, trusted};
use super::mac_keys;
use crate::clock;

/// `NSPasteboardTypeString`.
pub const TEXT: &str = "public.utf8-plain-text";
pub const CONCEALED: &str = "org.nspasteboard.ConcealedType";
/// What the promise is declared as besides the text.
pub const PROMISE_MARKERS: [&str; 3] = [
    "org.nspasteboard.TransientType",
    CONCEALED,
    "org.nspasteboard.AutoGeneratedType",
];

/// The worker's wait on macOS (`live::serve_with`): a turn of the main run loop, where AppKit
/// serves the pasteboard promise, then the next message. Runs on the main thread only.
pub fn wait(rx: &Receiver<Msg>, step: Duration) -> Result<Msg, RecvTimeoutError> {
    if let Ok(m) = rx.try_recv() {
        return Ok(m);
    }
    // SAFETY: a CF constant.
    let mode = unsafe { kCFRunLoopDefaultMode };
    // With nothing on the run loop yet (no promise was ever made) it returns at once: wait on
    // the queue instead of spinning.
    if CFRunLoop::run_in_mode(mode, step.as_secs_f64(), true) == CFRunLoopRunResult::Finished {
        return rx.recv_timeout(step);
    }
    rx.try_recv().map_err(|e| match e {
        TryRecvError::Empty => RecvTimeoutError::Timeout,
        TryRecvError::Disconnected => RecvTimeoutError::Disconnected,
    })
}

// ---------------------------------------------------------------------------
// The pasteboard

#[derive(Default)]
struct Promise {
    text: String,
    /// When the text was read, on the awake clock the worker uses.
    reads: Vec<u64>,
}

define_class!(
    // SAFETY: NSObject has no subclassing requirements; the ivars are plain Rust values that only
    // the main thread touches, which is where AppKit calls a pasteboard owner.
    #[unsafe(super(NSObject))]
    #[name = "AkouDictatePromise"]
    #[ivars = Rc<RefCell<Promise>>]
    struct PromiseOwner;

    impl PromiseOwner {
        /// An app asked for the promised data: the read receipt when it asked for the text.
        #[unsafe(method(pasteboard:provideDataForType:))]
        fn provide(&self, pasteboard: &AnyObject, ty: &NSString) {
            let payload = {
                let mut p = self.ivars().borrow_mut();
                if ty.to_string() == TEXT {
                    p.reads.push(clock::now().awake_ns);
                    p.text.clone()
                } else {
                    // A marker type carries nothing.
                    String::new()
                }
            };
            let s = NSString::from_str(&payload);
            // SAFETY: `setString:forType:` takes two NSStrings and returns a BOOL.
            let _: bool = unsafe { msg_send![pasteboard, setString: &*s, forType: ty] };
        }
    }
);

impl PromiseOwner {
    fn new(state: Rc<RefCell<Promise>>) -> Retained<Self> {
        let this = Self::alloc().set_ivars(state);
        // SAFETY: NSObject's designated initialiser.
        unsafe { msg_send![super(this), init] }
    }
}

pub struct Pasteboard {
    pb: Retained<AnyObject>,
    state: Rc<RefCell<Promise>>,
    /// The owner of the current promise; the pasteboard does not keep it alive.
    owner: Option<Retained<PromiseOwner>>,
}

fn nsstr(s: &str) -> Retained<NSString> {
    NSString::from_str(s)
}

impl Pasteboard {
    fn with(pb: Retained<AnyObject>) -> Pasteboard {
        Pasteboard {
            pb,
            state: Rc::default(),
            owner: None,
        }
    }

    /// The general pasteboard, the one Command+V reads.
    pub fn general() -> Option<Pasteboard> {
        let cls = AnyClass::get(c"NSPasteboard")?;
        // SAFETY: a class method returning the shared NSPasteboard.
        let pb: Option<Retained<AnyObject>> = unsafe { msg_send![cls, generalPasteboard] };
        pb.map(Pasteboard::with)
    }

    /// A private pasteboard by name (the tests': never the one the user copies to).
    pub fn named(name: &str) -> Option<Pasteboard> {
        let cls = AnyClass::get(c"NSPasteboard")?;
        let n = nsstr(name);
        // SAFETY: a class method taking an NSString and returning an NSPasteboard.
        let pb: Option<Retained<AnyObject>> = unsafe { msg_send![cls, pasteboardWithName: &*n] };
        pb.map(Pasteboard::with)
    }

    /// Frees a named pasteboard.
    pub fn release_globally(&self) {
        // SAFETY: no arguments, no result.
        let _: () = unsafe { msg_send![&*self.pb, releaseGlobally] };
    }

    fn clear(&mut self) {
        self.owner = None;
        // SAFETY: returns the new change count, unused here.
        let _: isize = unsafe { msg_send![&*self.pb, clearContents] };
    }
}

impl Clipboard for Pasteboard {
    fn snapshot(&mut self) -> Snapshot {
        autoreleasepool(|_| {
            let mut out = Vec::new();
            // SAFETY: `pasteboardItems` returns an NSArray of NSPasteboardItem, or nil.
            let items: Option<Retained<NSArray<AnyObject>>> =
                unsafe { msg_send![&*self.pb, pasteboardItems] };
            for (i, item) in items.iter().flat_map(|a| a.iter()).enumerate() {
                // SAFETY: `types` returns an NSArray of NSString.
                let types: Option<Retained<NSArray<NSString>>> =
                    unsafe { msg_send![&*item, types] };
                for ty in types.iter().flat_map(|a| a.iter()) {
                    // SAFETY: `dataForType:` takes an NSString and returns NSData or nil.
                    let data: Option<Retained<NSData>> =
                        unsafe { msg_send![&*item, dataForType: &*ty] };
                    if let Some(d) = data {
                        out.push((format!("{i}\t{ty}"), d.to_vec()));
                    }
                }
            }
            out
        })
    }

    fn publish(&mut self, text: &str) -> Result<u64, String> {
        autoreleasepool(|_| {
            // A fresh record per promise: a late read of an older one lands nowhere.
            self.state = Rc::new(RefCell::new(Promise {
                text: text.to_string(),
                reads: Vec::new(),
            }));
            let owner = PromiseOwner::new(self.state.clone());
            let types: Vec<Retained<NSString>> = std::iter::once(TEXT)
                .chain(PROMISE_MARKERS)
                .map(nsstr)
                .collect();
            let types = NSArray::from_retained_slice(&types);
            // SAFETY: `declareTypes:owner:` takes an NSArray of NSString and any object, and
            // returns the new change count.
            let count: isize =
                unsafe { msg_send![&*self.pb, declareTypes: &*types, owner: &*owner] };
            self.owner = Some(owner);
            if count <= 0 {
                return Err("clipboard-publish".into());
            }
            Ok(count as u64)
        })
    }

    fn write(&mut self, text: &str, concealed: bool) -> Result<(), String> {
        autoreleasepool(|_| {
            self.clear();
            let (s, ty) = (nsstr(text), nsstr(TEXT));
            // SAFETY: `setString:forType:` takes two NSStrings and returns a BOOL.
            let ok: bool = unsafe { msg_send![&*self.pb, setString: &*s, forType: &*ty] };
            if ok && concealed {
                let (empty, marker) = (NSData::with_bytes(&[]), nsstr(CONCEALED));
                // SAFETY: `setData:forType:` takes NSData and an NSString and returns a BOOL.
                let _: bool = unsafe { msg_send![&*self.pb, setData: &*empty, forType: &*marker] };
            }
            if ok {
                Ok(())
            } else {
                Err("clipboard-write".into())
            }
        })
    }

    fn change_count(&mut self) -> u64 {
        // SAFETY: returns an NSInteger.
        let c: isize = unsafe { msg_send![&*self.pb, changeCount] };
        c.max(0) as u64
    }

    fn restore(&mut self, snapshot: &Snapshot) {
        autoreleasepool(|_| {
            self.clear();
            let Some(cls) = AnyClass::get(c"NSPasteboardItem") else {
                return;
            };
            let mut items: Vec<Retained<AnyObject>> = Vec::new();
            let mut index = None;
            for (key, bytes) in snapshot {
                let Some((i, ty)) = key.split_once('\t') else {
                    continue;
                };
                if index != Some(i) {
                    // SAFETY: `new` returns a +1 NSPasteboardItem.
                    items.push(unsafe { msg_send![cls, new] });
                    index = Some(i);
                }
                let Some(item) = items.last() else { continue };
                let (d, t) = (NSData::with_bytes(bytes), nsstr(ty));
                // SAFETY: `setData:forType:` takes NSData and an NSString and returns a BOOL.
                let _: bool = unsafe { msg_send![&**item, setData: &*d, forType: &*t] };
            }
            if !items.is_empty() {
                let items = NSArray::from_retained_slice(&items);
                // SAFETY: `writeObjects:` takes an NSArray of pasteboard writers.
                let _: bool = unsafe { msg_send![&*self.pb, writeObjects: &*items] };
            }
        });
    }

    fn reads(&mut self) -> Vec<u64> {
        std::mem::take(&mut self.state.borrow_mut().reads)
    }
}

// ---------------------------------------------------------------------------
// The events

pub struct Events {
    source: CFRetained<CGEventSource>,
}

impl Events {
    pub fn new() -> Option<Events> {
        let source = CGEventSource::new(CGEventSourceStateID::Private)?;
        CGEventSource::set_user_data(Some(&source), AKOU_EVENT);
        Some(Events { source })
    }

    fn event(
        &self,
        code: u16,
        down: bool,
        flags: u64,
        modifier: bool,
    ) -> Result<CFRetained<CGEvent>, String> {
        let e =
            CGEvent::new_keyboard_event(Some(&self.source), code, down).ok_or("no-key-event")?;
        if modifier {
            CGEvent::set_type(Some(&e), CGEventType::FlagsChanged);
        }
        CGEvent::set_flags(Some(&e), CGEventFlags(flags));
        CGEvent::set_integer_value_field(Some(&e), CGEventField::EventSourceUserData, AKOU_EVENT);
        Ok(e)
    }

    /// `mods` then `code`: each modifier down, the key down and up with the modifiers' flags,
    /// the modifiers up in reverse.
    pub fn chord(&self, mods: &[&str], code: u16) -> Result<Vec<CFRetained<CGEvent>>, String> {
        let keys = mods
            .iter()
            .map(|m| mac_keys::modifier_key(m).ok_or_else(|| format!("no-modifier {m}")))
            .collect::<Result<Vec<_>, _>>()?;
        let mut out = Vec::new();
        let mut flags = 0;
        for (c, f) in &keys {
            flags |= f;
            out.push(self.event(*c, true, flags, true)?);
        }
        out.push(self.event(code, true, flags, false)?);
        out.push(self.event(code, false, flags, false)?);
        for (c, f) in keys.iter().rev() {
            flags &= !f;
            out.push(self.event(*c, false, flags, true)?);
        }
        Ok(out)
    }

    /// One piece of the typed path as a key-down and a key-up carrying it.
    pub fn text(&self, text: &str) -> Result<Vec<CFRetained<CGEvent>>, String> {
        let units: Vec<u16> = text.encode_utf16().collect();
        if units.len() > TYPE_CHUNK || text.contains(['\n', '\r']) {
            return Err("type-piece".into());
        }
        [true, false]
            .into_iter()
            .map(|down| {
                let e = self.event(0, down, 0, false)?;
                // SAFETY: `units` holds `units.len()` UTF-16 units and outlives the call.
                unsafe {
                    CGEvent::keyboard_set_unicode_string(Some(&e), units.len() as _, units.as_ptr())
                };
                Ok(e)
            })
            .collect()
    }

    fn post(&self, events: Vec<CFRetained<CGEvent>>) -> Result<(), String> {
        if !trusted() {
            return Err("no-grant".into());
        }
        for e in events {
            CGEvent::post(CGEventTapLocation::HIDEventTap, Some(&e));
        }
        Ok(())
    }
}

fn flags_now() -> u64 {
    CGEventSource::flags_state(CGEventSourceStateID::CombinedSessionState).0
}

impl Sink for Events {
    fn held_modifiers(&mut self) -> Vec<String> {
        mac_keys::held_modifiers(flags_now())
    }

    fn modifier(&mut self, name: &str, down: bool) -> Result<(), String> {
        let (code, f) =
            mac_keys::modifier_key(name).ok_or_else(|| format!("no-modifier {name}"))?;
        let flags = if down {
            flags_now() | f
        } else {
            flags_now() & !f
        };
        let e = self.event(code, down, flags, true)?;
        self.post(vec![e])
    }

    fn press(&mut self, mods: &[&str], key: Key) -> Result<(), String> {
        let code = match key {
            Key::Code(c) => c,
            Key::Named(n) => mac_keys::key_code(n).ok_or_else(|| format!("no-key {n}"))?,
        };
        let events = self.chord(mods, code)?;
        self.post(events)
    }

    fn keycode(&mut self, ch: char) -> Option<u16> {
        layout::keycode(ch)
    }

    fn type_text(&mut self, text: &str) -> Result<(), String> {
        let events = self.text(text)?;
        self.post(events)
    }
}

// ---------------------------------------------------------------------------
// The keyboard layout

pub mod layout {
    use super::*;

    #[link(name = "Carbon", kind = "framework")]
    unsafe extern "C" {
        fn TISCopyCurrentKeyboardLayoutInputSource() -> *const c_void;
        fn TISCopyCurrentASCIICapableKeyboardLayoutInputSource() -> *const c_void;
        fn TISCreateInputSourceList(properties: *const c_void, all_installed: u8) -> *const c_void;
        fn TISGetInputSourceProperty(source: *const c_void, key: *const c_void) -> *const c_void;
        static kTISPropertyUnicodeKeyLayoutData: *const c_void;
        static kTISPropertyInputSourceID: *const c_void;
        fn LMGetKbdType() -> u8;
        fn UCKeyTranslate(
            layout: *const c_void,
            code: u16,
            action: u16,
            modifiers: u32,
            keyboard_type: u32,
            options: u32,
            dead_key_state: *mut u32,
            max_len: usize,
            len: *mut usize,
            out: *mut u16,
        ) -> i32;
    }

    #[link(name = "CoreFoundation", kind = "framework")]
    unsafe extern "C" {
        fn CFRelease(cf: *const c_void);
        fn CFArrayGetCount(array: *const c_void) -> isize;
        fn CFArrayGetValueAtIndex(array: *const c_void, i: isize) -> *const c_void;
        fn CFDataGetBytePtr(data: *const c_void) -> *const u8;
    }

    /// `kUCKeyActionDisplay`, `cmdKey >> 8`, `kUCKeyTranslateNoDeadKeysMask`.
    const DISPLAY: u16 = 3;
    const COMMAND: u32 = 1;
    const NO_DEAD_KEYS: u32 = 1;

    /// The key code that types `ch` on the `uchr` layout data, with Command held or not.
    ///
    /// # Safety
    /// `uchr` points to a live `UCKeyboardLayout`.
    unsafe fn find(uchr: *const c_void, ch: char, command: bool) -> Option<u16> {
        let mut want = [0u16; 2];
        let want = ch.encode_utf16(&mut want);
        // SAFETY: no arguments.
        let kbd = u32::from(unsafe { LMGetKbdType() });
        (0..128u16).find(|&code| {
            let (mut dead, mut len, mut buf) = (0u32, 0usize, [0u16; 4]);
            // SAFETY: every pointer is to a local of the size given.
            let err = unsafe {
                UCKeyTranslate(
                    uchr,
                    code,
                    DISPLAY,
                    if command { COMMAND } else { 0 },
                    kbd,
                    NO_DEAD_KEYS,
                    &mut dead,
                    buf.len(),
                    &mut len,
                    buf.as_mut_ptr(),
                )
            };
            err == 0 && buf[..len.min(buf.len())] == *want
        })
    }

    /// # Safety
    /// `source` is a live `TISInputSourceRef` or null.
    unsafe fn in_source(source: *const c_void, ch: char) -> Option<u16> {
        if source.is_null() {
            return None;
        }
        // SAFETY: a live source and a TIS constant; the data belongs to the source.
        let data = unsafe { TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) };
        if data.is_null() {
            return None;
        }
        // SAFETY: the property is a CFData holding the layout.
        let uchr = unsafe { CFDataGetBytePtr(data) }.cast::<c_void>();
        // SAFETY: the layout lives as long as `source`.
        unsafe { find(uchr, ch, true).or_else(|| find(uchr, ch, false)) }
    }

    /// The key code that types `ch` on the active layout, else on the ASCII-capable layout macOS
    /// uses for shortcuts. Main thread only.
    pub fn keycode(ch: char) -> Option<u16> {
        let copies: [unsafe extern "C" fn() -> *const c_void; 2] = [
            TISCopyCurrentKeyboardLayoutInputSource,
            TISCopyCurrentASCIICapableKeyboardLayoutInputSource,
        ];
        copies.into_iter().find_map(|copy| {
            // SAFETY: returns a +1 source or null, released below.
            let source = unsafe { copy() };
            // SAFETY: `source` is live until released.
            let found = unsafe { in_source(source, ch) };
            if !source.is_null() {
                // SAFETY: the +1 reference from the copy.
                unsafe { CFRelease(source) };
            }
            found
        })
    }

    /// The same on the installed layout `id` (`com.apple.keylayout.Dvorak`), selected or not;
    /// `None` when no such layout is installed. Main thread only.
    pub fn keycode_in(id: &str, ch: char) -> Option<Option<u16>> {
        // SAFETY: a +1 CFArray of every installed source, released below.
        let list = unsafe { TISCreateInputSourceList(std::ptr::null(), 1) };
        if list.is_null() {
            return None;
        }
        let mut out = None;
        // SAFETY: `list` is a live CFArray; its values are TISInputSourceRefs it owns.
        for i in 0..unsafe { CFArrayGetCount(list) } {
            let source = unsafe { CFArrayGetValueAtIndex(list, i) };
            let name = unsafe { TISGetInputSourceProperty(source, kTISPropertyInputSourceID) };
            // SAFETY: the source id is a CFString owned by the source.
            let name = unsafe { name.cast::<CFString>().as_ref() }.map(ToString::to_string);
            if name.as_deref() == Some(id) {
                out = Some(unsafe { in_source(source, ch) });
                break;
            }
        }
        // SAFETY: the +1 reference from the create.
        unsafe { CFRelease(list) };
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn read(e: &CGEvent) -> (i64, u64, i64, CGEventType) {
        (
            CGEvent::integer_value_field(Some(e), CGEventField::KeyboardEventKeycode),
            CGEvent::flags(Some(e)).0,
            CGEvent::integer_value_field(Some(e), CGEventField::EventSourceUserData),
            CGEvent::r#type(Some(e)),
        )
    }

    /// DC-N6: Command+V is Command down, V down and up with the Command flag, Command up, every
    /// event marked as the helper's own so its tap lets it pass. Built, never posted.
    #[test]
    fn dc_n6_the_paste_chord_is_command_down_v_command_up() {
        use mac_keys::flag::{COMMAND, LEFT_COMMAND};
        let ev = Events::new().unwrap();
        let chord = ev.chord(&["Command"], 47).unwrap();
        let cmd = COMMAND | LEFT_COMMAND;
        let got: Vec<_> = chord.iter().map(|e| read(e)).collect();
        assert_eq!(
            got,
            [
                (0x37, cmd, AKOU_EVENT, CGEventType::FlagsChanged),
                (47, cmd, AKOU_EVENT, CGEventType::KeyDown),
                (47, cmd, AKOU_EVENT, CGEventType::KeyUp),
                (0x37, 0, AKOU_EVENT, CGEventType::FlagsChanged),
            ]
        );
        assert!(ev.chord(&["Hyper"], 9).is_err());
        let enter = ev.chord(&[], 0x24).unwrap();
        assert_eq!(enter.len(), 2, "a bare send key is one press");
    }

    /// DC-N7: a piece is one key-down and one key-up carrying it whole, emoji included; a piece
    /// over 20 units or with a newline is refused, never cut.
    #[test]
    fn dc_n7_a_typed_piece_rides_on_its_events() {
        let ev = Events::new().unwrap();
        let piece = "héllo 😀 wörld";
        let events = ev.text(piece).unwrap();
        assert_eq!(events.len(), 2);
        for e in &events {
            let mut buf = [0u16; 32];
            let mut len = 0;
            // SAFETY: `buf` holds 32 units.
            unsafe {
                CGEvent::keyboard_get_unicode_string(
                    Some(e),
                    buf.len() as _,
                    &mut len,
                    buf.as_mut_ptr(),
                )
            };
            assert_eq!(String::from_utf16(&buf[..len as usize]).unwrap(), piece);
            assert_eq!(read(e).2, AKOU_EVENT);
        }
        assert_eq!(read(&events[0]).3, CGEventType::KeyDown);
        assert_eq!(read(&events[1]).3, CGEventType::KeyUp);
        assert!(ev.text(&"a".repeat(TYPE_CHUNK + 1)).is_err());
        assert!(ev.text("a\nb").is_err());
    }
}
