/**
 * Writes the CLI reference, `docs/cli.md` (docs/ux/CLI.md CLI-31): every command's help page from
 * the command registry, then the door parity table from `tests/contracts/parity.ts` (TS-13). The
 * file is generated, never edited: `tests/cli-reference.test.ts` regenerates it on every CI run
 * and fails when the committed copy differs.
 *
 *   bun scripts/cli-reference.ts           write the file
 *   bun scripts/cli-reference.ts --check   exit 1 when the committed file differs from the registry
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { COMMANDS } from "../src/main/cli/cli.ts";
import type { Command } from "../src/main/cli/context.ts";
import { commandHelp } from "../src/main/cli/help.ts";
import { PARITY, type Row } from "../tests/contracts/parity.ts";

export const CLI_REFERENCE_FILE = join(import.meta.dir, "..", "docs", "cli.md");

/** One table cell: no line breaks and no bare pipes. */
const cell = (s: string) => s.replace(/\s+/g, " ").replaceAll("|", "\\|");
const code = (s: string) => `\`${s.replaceAll("|", "\\|")}\``;

function door(c: Row["cli"] | Row["window"]): string {
  if (!Array.isArray(c)) return `none: ${cell((c as { none: string }).none)}`;
  const names = c.map((x) => (typeof x === "string" ? x : x.file));
  return [...new Set(names)].map(code).join(", ");
}

/** The page as the registry and the parity table generate it, byte for byte. */
export function renderCliReference(
  commands: readonly Command[] = COMMANDS,
  parity: readonly Row[] = PARITY,
): string {
  const pages = commands.map((c) => `## ${c.name}\n\n\`\`\`text\n${commandHelp(c)}\n\`\`\`\n`);
  const rows = parity.map(
    (r) =>
      `| ${cell(r.action)} | ${door(r.cli)} | ${door(r.api)} | ${door(r.mcp)} | ${door(r.window)} |`,
  );
  return [
    "<!-- Generated by scripts/cli-reference.ts from the command registry and tests/contracts/parity.ts. Do not edit: run bun scripts/cli-reference.ts. -->",
    "",
    "# Command-line reference",
    "",
    "Every `akou` command with its help page, exactly as `akou help COMMAND` prints it, then the table of what each action is called through the command line, the HTTP API, MCP and the window. The page is generated from the code, and CI fails when it differs.",
    "",
    "Exit codes: 0 ok, 3 nothing live, 64 usage, 65 bad vocabulary term, 69 unavailable, 70 software, 75 already recording, 77 permission, 78 the settings refuse it, 124 timed out.",
    "",
    ...pages,
    "## Door parity",
    "",
    "| Action | CLI | API | MCP | Window |",
    "|---|---|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}

/** Whether the committed file is exactly the generated one (line endings aside). */
export function cliReferenceDrifted(committed: string, generated = renderCliReference()): boolean {
  return committed.replace(/\r\n/g, "\n") !== generated;
}

if (import.meta.main) {
  const generated = renderCliReference();
  if (process.argv.includes("--check")) {
    const committed = existsSync(CLI_REFERENCE_FILE)
      ? readFileSync(CLI_REFERENCE_FILE, "utf8")
      : "";
    if (cliReferenceDrifted(committed, generated)) {
      console.error(
        "docs/cli.md differs from the command registry: run bun scripts/cli-reference.ts",
      );
      process.exit(1);
    }
  } else {
    writeFileSync(CLI_REFERENCE_FILE, generated);
  }
}
