/**
 * Writes the MCP tool reference, `docs/reference/mcp.md`, from the server's own `tools/list`
 * (docs/TESTING.md TS-12). The page is generated, never edited: `tests/mcp-reference.test.ts`
 * regenerates it on every CI run and fails when the committed copy differs.
 *
 *   bun scripts/mcp-reference.ts           write the page
 *   bun scripts/mcp-reference.ts --check   exit 1 when the committed page differs from the server
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { Client, type Tool } from "@modelcontextprotocol/client";
import { InMemoryTransport } from "@modelcontextprotocol/server";
import type { ApiClient, ApiResponse } from "../src/main/cli/client.ts";
import { createMcpServer } from "../src/main/mcp/server.ts";

export const MCP_REFERENCE_FILE = join(import.meta.dir, "..", "docs", "reference", "mcp.md");

/**
 * Every tool the server lists, by name. The list is pinned to the case where everything is
 * listed: the app's provider can answer and is not the client's own harness, so `akou_ask` is in.
 */
export async function listMcpTools(): Promise<Tool[]> {
  let statusRead: () => void = () => {};
  const read = new Promise<void>((r) => {
    statusRead = r;
  });
  const api = {
    request: async (_method: string, path: string): Promise<ApiResponse> => {
      const body = path === "/status" ? { provider: { state: "available", id: "anthropic" } } : {};
      if (path === "/status") queueMicrotask(statusRead);
      return { status: 200, body, text: JSON.stringify(body), contentType: "application/json" };
    },
  } as unknown as ApiClient;
  const server = createMcpServer({ client: api });
  const [a, b] = InMemoryTransport.createLinkedPair();
  await server.connect(b);
  const client = new Client({ name: "akou-reference", version: "1.0.0" });
  await client.connect(a);
  try {
    // The server reads the provider right after initialize, then lists akou_ask.
    await read;
    await new Promise((r) => setTimeout(r, 0));
    const tools = (await client.listTools()).tools;
    return [...tools].sort((x, y) => x.name.localeCompare(y.name));
  } finally {
    await client.close();
  }
}

/** Text for Markdown prose: `<` and `>` escaped outside code spans, so `<call-text>` shows. */
function prose(s: string): string {
  return s
    .split(/(`[^`]*`)/)
    .map((part, i) => (i % 2 === 1 ? part : part.replace(/</g, "&lt;").replace(/>/g, "&gt;")))
    .join("");
}

/** Text inside a table cell: a backslash or a pipe of its own never ends the cell. */
function pipeSafe(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\|/g, "\\|");
}

/** Text for a table cell: one line, no unescaped pipe. */
function cell(s: string): string {
  return pipeSafe(prose(s.replace(/\s*\n\s*/g, " ")));
}

type Schema = Record<string, unknown>;

/** A JSON schema's type in a few words: `string`, `string[]`, `"a" or "b"`, `object`. */
function typeOf(s: Schema | undefined): string {
  if (!s) return "any";
  if (Array.isArray(s.enum)) return s.enum.map((v) => JSON.stringify(v)).join(" or ");
  if ("const" in s) return JSON.stringify(s.const);
  const alts = (s.anyOf ?? s.oneOf) as Schema[] | undefined;
  if (Array.isArray(alts)) return alts.map(typeOf).join(" or ");
  if (Array.isArray(s.type)) return s.type.join(" or ");
  if (s.type === "array") return `${typeOf(s.items as Schema | undefined)}[]`;
  return typeof s.type === "string" ? s.type : "any";
}

function renderTool(t: Tool): string {
  const out = [`## ${t.name}`, ""];
  if (t.title) out.push(`**${prose(t.title)}**`, "");
  if (t.description) out.push(prose(t.description), "");
  const hints = Object.entries(t.annotations ?? {}).filter(([k]) => k !== "title");
  out.push(
    `Annotations: ${hints.length ? hints.map(([k, v]) => `\`${k}: ${v}\``).join(", ") : "none"}.`,
    "",
  );
  const schema = t.inputSchema as Schema;
  const props = Object.entries((schema.properties ?? {}) as Record<string, Schema>);
  const required = new Set((schema.required ?? []) as string[]);
  if (props.length === 0) {
    out.push("Parameters: none.", "");
  } else {
    out.push("| Parameter | Type | Required | Description |", "|---|---|---|---|");
    for (const [name, p] of props) {
      const desc = typeof p.description === "string" ? cell(p.description) : "";
      out.push(
        `| \`${name}\` | \`${typeOf(p).replace(/\|/g, "\\|")}\` | ${required.has(name) ? "yes" : "no"} | ${desc} |`,
      );
    }
    out.push("");
  }
  out.push(
    "<details markdown>",
    "<summary>Input schema</summary>",
    "",
    "```json",
    JSON.stringify(t.inputSchema, null, 2),
    "```",
    "",
    "</details>",
    "",
  );
  return out.join("\n");
}

/** The page as the tool list generates it, byte for byte. */
export function renderMcpReference(tools: readonly Tool[]): string {
  const head = [
    "<!-- Generated by scripts/mcp-reference.ts from the MCP server's tools/list. Do not edit: run bun run mcp-reference. -->",
    "",
    "# MCP tools",
    "",
    "Every tool `akou mcp` lists, with its parameters and the annotations a harness reads to decide which tools it may run without asking. The server answers from the local API, so each tool does what the matching command or route does. `akou_ask` is listed only while akou's provider can answer, and never to a client that is itself that provider's harness. The page is generated from the server's tool list, and CI fails when it differs.",
    "",
  ];
  return `${[...head, ...tools.map(renderTool)].join("\n").trimEnd()}\n`;
}

/** Whether the committed page is exactly the generated one (line endings aside). */
export function mcpReferenceDrifted(committed: string, generated: string): boolean {
  return committed.replace(/\r\n/g, "\n") !== generated;
}

if (import.meta.main) {
  const generated = renderMcpReference(await listMcpTools());
  if (process.argv.includes("--check")) {
    const committed = existsSync(MCP_REFERENCE_FILE)
      ? readFileSync(MCP_REFERENCE_FILE, "utf8")
      : "";
    if (mcpReferenceDrifted(committed, generated)) {
      console.error(
        "docs/reference/mcp.md differs from the MCP server's tools: run bun run mcp-reference",
      );
      process.exit(1);
    }
  } else {
    mkdirSync(dirname(MCP_REFERENCE_FILE), { recursive: true });
    writeFileSync(MCP_REFERENCE_FILE, generated);
  }
}
