/**
 * Writes the settings tables of `docs/configuration.md` from the settings registry
 * (`src/main/config/schema.ts`), so the page never drifts from the code. Everything above the
 * marker line is hand-written and kept; everything below it is replaced.
 *
 *   bun scripts/settings-doc.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { SETTINGS, type SettingSpec } from "../src/main/config/schema.ts";

const PAGE = join(import.meta.dir, "..", "docs", "configuration.md");
const MARKER = "<!-- Generated by scripts/settings-doc.ts from the settings registry. -->";

/** One table cell: no line breaks, no bare pipes, and the home folder as `~`. */
const cell = (s: string) =>
  s.replaceAll(homedir(), "~").replace(/\s+/g, " ").replaceAll("|", "\\|");

const groups = new Map<string, string[]>();
for (const [key, spec] of Object.entries(SETTINGS as Record<string, SettingSpec>)) {
  const group = key.split(".")[0] ?? key;
  const where =
    spec.apiWritable === false ? (spec.windowWritable ? " (window or file)" : " (file only)") : "";
  const row = `| \`${key}\`${where} | \`${cell(JSON.stringify(spec.default))}\` | ${cell(spec.doc)} |`;
  groups.set(group, [...(groups.get(group) ?? []), row]);
}

const tables = [...groups].map(
  ([group, rows]) =>
    `### ${group}\n\n| Key | Default | What it does |\n|---|---|---|\n${rows.join("\n")}\n`,
);
const head = readFileSync(PAGE, "utf8").split(MARKER)[0] ?? "";
writeFileSync(PAGE, `${head}${MARKER}\n\n${tables.join("\n")}`);
