/**
 * Writes the settings tables of `docs/configuration.md` from the settings registry
 * (`src/main/config/schema.ts`), so the page never drifts from the code ([T1.39], TS-9).
 * Everything above the marker line is hand-written and kept; everything below it is replaced.
 * Defaults that depend on the machine are written as they are on macOS, on any OS.
 *
 *   bun scripts/settings-doc.ts            rewrite the page
 *   bun scripts/settings-doc.ts --check    fail when the page differs from what it would write
 */

import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { defaultModelsDir } from "../src/main/asr/models.ts";
import { pillDefault, SETTINGS, type SettingSpec } from "../src/main/config/schema.ts";

export const PAGE = join(import.meta.dir, "..", "docs", "configuration.md");
export const MARKER = "<!-- Generated by scripts/settings-doc.ts from the settings registry. -->";

/** A path under the home folder as `~/...`, with forward slashes on every OS. */
const tilde = (s: string) =>
  s.startsWith(homedir()) ? `~${s.slice(homedir().length).replaceAll("\\", "/")}` : s;

/** One table cell: no line breaks, no bare pipes, and the home folder as `~`. */
const cell = (s: string) =>
  s.replaceAll(homedir(), "~").replace(/\s+/g, " ").replaceAll("|", "\\|");

/** The default the page shows: the macOS one where the default depends on the machine. */
function shown(key: string, spec: SettingSpec): unknown {
  if (key === "recordings.root") return tilde(join(homedir(), "Recordings", "akou"));
  if (key === "asr.modelsDir") return tilde(defaultModelsDir({}, "darwin"));
  if (key === "dictation.pill") return pillDefault("darwin");
  return spec.default;
}

/** The whole page: the hand-written head of `page`, the marker, then one table per group. */
export function render(page: string, settings: Record<string, SettingSpec> = SETTINGS): string {
  const groups = new Map<string, string[]>();
  for (const [key, spec] of Object.entries(settings)) {
    const group = key.split(".")[0] ?? key;
    const where =
      spec.apiWritable === false
        ? spec.windowWritable
          ? " (window or file)"
          : " (file only)"
        : "";
    const row = `| \`${key}\`${where} | \`${cell(JSON.stringify(shown(key, spec)))}\` | ${cell(spec.doc)} |`;
    groups.set(group, [...(groups.get(group) ?? []), row]);
  }
  const tables = [...groups].map(
    ([group, rows]) =>
      `### ${group}\n\n| Key | Default | What it does |\n|---|---|---|\n${rows.join("\n")}\n`,
  );
  const head = page.split(MARKER)[0] ?? "";
  return `${head}${MARKER}\n\n${tables.join("\n")}`;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const check = args.includes("--check");
  const page = args.find((a) => a !== "--check") ?? PAGE;
  const now = readFileSync(page, "utf8").replaceAll("\r\n", "\n");
  const want = render(now);
  if (!check) writeFileSync(page, want);
  else if (now !== want) {
    const a = now.split("\n");
    const b = want.split("\n");
    const at = a.findIndex((l, i) => l !== b[i]);
    console.error(
      `settings-doc: ${page} differs from the settings registry, first at line ${at + 1}:\n  page:     ${a[at] ?? "(end)"}\n  registry: ${b[at] ?? "(end)"}\nRun \`bun scripts/settings-doc.ts\` and commit the page.`,
    );
    process.exit(1);
  }
}
